### ISSUE TITLE
Consolidate Ruby vs JS language pages under the same "Develop" title

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.github.io#104]
We should start differentiating Ruby and JS and have pages separate for them. Because we also want to add a Python version for interscript too.

We have the "Integrate" "Develop" "Convert using API" "Convert using JS" pages. I think we can streamline them in some way...

Maybe easier to have a page called "Use" vs "Develop" too.

Maybe under "Develop" we should have documentation for various usage cases... and allow people to choose between languages?

**Comment by webdev778** [comment]
My proposal for website redesign:

- Remove "Authorities" tab - it basically does the same thing as "Systems" tab, and Authorities are described better in the "Featured authorities" section
- Replace "Integrate" and "Develop" tabs with "Use in your application" and "Create maps". The part "Use in your application" would be divided into sections with contents from old sections:
  - Use in your application
    - Ruby and command line
        - command line utility
        - Integration with Ruby
        - Usage with Rababa
        - Usage with Secryst
    - JavaScript
    - API? (Is API actually public?)
  - Create maps
    - Map Editing Guide
    - Interscript Map Format
    - Maintainers
- Join "Convert using API" and "Convert using JS" pages. Use API by default, add a checkbox/radio/select
- Join all "Convert", "Detect systems", "Diacritize scripts" as a section "Demo"
- Replace the website header with one of the three proposals:
  - Proposal 1: Gives an easy access to the Interscript features (Attachment 1)
  - Proposal 2: In addition, gives user an immediate feedback which programming languages are supported (Attachment 2)
  - Proposal 3: Perhaps instead of the "Use Interscript in your application" part, just show programming language icons

![image](https://github.com/interscript/interscript.github.io/assets/28761746/f37f11bb-bd14-4802-b0c5-671013eafe74)
![image1](https://github.com/interscript/interscript.github.io/assets/28761746/5cbfa0de-e151-41b8-a5fb-aa77a6483af5)

**Comment by ronaldtse** [comment]
@webdev778 please help proceed with these changes.

For the header, I think the "Try interscript" part can be incorporated on the front page directly?

**Comment by webdev778** [comment]
![image](https://github.com/interscript/interscript.github.io/assets/28761746/05b56c97-6af6-4002-8054-d0153d0acda1)

Done with the PRs #105 , #106
